export const GET_ALL_MARKETPLACE_CATEGORIES = 'get_all_marketplace_categories';
export const GET_ALL_MARKETPLACE_CATEGORIES_SUCCESS = 'get_all_marketplace_categories_success';
export const GET_ALL_MARKETPLACE_NFTS_BY_CATEGORY = 'get_all_marketplace_nfts_by_categories';
export const GET_ALL_MARKETPLACE_NFTS_BY_CATEGORY_SUCCESS = 'get_all_marketplace_nfts_by_categories_success';
export const GET_ALL_SIMILAR_PRODUCTS = 'get_all_similar_products';
export const GET_ALL_SIMILAR_PRODUCTS_SUCCESS = 'get_all_similar_products_success';